# Generated by Django 4.2.7 on 2023-12-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="username",),
    ]
