# Generated by Django 4.2.7 on 2023-12-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_user_username"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
