# Generated by Django 4.2.7 on 2023-12-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_delete_user"),
    ]

    operations = []
