# Generated by Django 4.2.7 on 2023-12-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
